### ISSUE TITLE
fatal error: GL/glew.h: No such file or directory

### ISSUE THREAD

**Issue by slowcheet4h** [sebbekarlsson/cengine#3]
In file included from src/include/sprite.h:5:0,
                 from src/include/actor.h:3,
                 from src/include/physics.h:3,
                 from src/physics.c:1:
src/include/draw.h:3:10: fatal error: GL/glew.h: No such file or directory
 #include <GL/glew.h>
          ^~~~~~~~~~~
compilation terminated.
Makefile:17: recipe for target 'src/physics.o' failed
make[1]: *** [src/physics.o] Error 1
Makefile:20: recipe for target 'install' failed
make: *** [install] Error 2

**Comment by sebbekarlsson** [comment]
You don't have Glew installed on your system, this is not an issue with this software

**Comment by slowcheet4h** [comment]
getpackages.sh should install it
